---
- name: Setting hostname
  hostname: name={{ hostname }}.{{ domain }}

- name: Update packages
  yum:
    name: "*"
    update_cache: yes
    state: latest

- name: Install useful packages
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - bash-completion
    